# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terragrunt-mystormbreakerbucket-thor"
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "ap-south-1"
  }
}
